version = 0.1
[default.deploy.parameters]
stack_name = "examgpt-backend"
resolve_s3 = true
s3_prefix = "examgpt-backend"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = false