AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  examgpt-backend

  Backend for examgpt. 
  * API gateway, Lambda and S3 used for uploading study material
  * DynamoDB, Lambda, SNS used for storing examgpt data
  * API Gateway, Lambda used for for telegram bot

Globals:
  Function:
    Runtime: python3.12
    Timeout: 300
    Environment:
      Variables:
        EXAM_TABLE: !Ref ExamTable

Resources:
  # S3 Buckets
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-bucket"

  # SNS Topics
  ChunksTopic:
    Type: AWS::SNS::Topic

  # DynamoDB
  ExamTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      KeySchema:
        - AttributeName: exam_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: exam_id
          AttributeType: S
      TableName: !Sub "${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-exam"

  # Rest APIs
  ExamGPTRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  # Lambda Functions
  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: upload.handler
      MemorySize: 128
      Environment:
        Variables:
          CONTENT_BUCKET: !Ref ContentBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ContentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ExamTable
      Events:
        APIEvent:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
            RestApiId: !Ref ExamGPTRestApi

  ChunkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: chunker.handler
      MemorySize: 512
      Environment:
        Variables:
          CHUNKS_TOPIC: !Ref ChunksTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ChunksTopic.TopicName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ContentBucket
            Events:
              - s3:ObjectCreated:*

  GenerateQAFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: generate.handler
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref ChunksTopic

  SandboxFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: sandbox.handler
      Events:
        APIEvent:
          Type: Api
          Properties:
            Path: /sandbox
            Method: POST
            RestApiId: !Ref ExamGPTRestApi

  # Connectors
  ChunkerFunctionContentBucketConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: ChunkerFunction
      Destination:
        Id: ContentBucket
      Permissions:
        - Read

Outputs:
  ExamGPTRestApi:
    Description: "API Gateway endpoint for uploading files"
    Value: !Sub "https://${ExamGPTRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage"
  # UploadFunction:
  #   Description: "Function that uploads file"
  #   Value: !GetAtt UploadFunction.Arn
  # ChunkerFunction:
  #   Description: "Function that chunks uploaded file"
  #   Value: !GetAtt ChunkerFunction.Arn
  # SandboxFunction:
  #   Description: "Sandbox Lambda for testing resources"
  #   Value: !GetAtt SandboxFunction.Arn
  # S3Bucket:
  #   Description: "Bucket where uploaded files are stored"
  #   Value: !GetAtt ContentBucket.Arn
