AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  examgpt-backend
  Backend for examgpt.  
  * API gateway, Lambda and S3 used for creating exam once file is uploaded to S3 by client 
  * DynamoDB, Lambda, SNS used for storing examgpt data 
  * API Gateway, Lambda used for for telegram bot

Globals:
  Function:
    Runtime: python3.12
    EventInvokeConfig:
      MaximumRetryAttempts: 1
    Environment:
      Variables:
        EXAM_TABLE: !Ref ExamTable
        LOCATION: AWS
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
    AlwaysDeploy: true

Resources:
  # S3 Buckets
  ContentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-bucket
      CorsConfiguration:
        CorsRules: # TODO: fix AllowedOrigins and AllowedMethods after front end deployment
          - AllowedHeaders:
              - "*"
            AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - PUT
              - POST
            MaxAge: 3000

  # SNS Topics
  ChunkTopic:
    Type: AWS::SNS::Topic

  # Parameter Store
  # Deploys parameters with dummy values. Update these with real values using
  # scripts/store_env_in_cloud.sh
  ParameterStoreOpenAIKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /examgpt/OPENAI_API_KEY
      Type: String
      Description: OPENAI API key
      Value: OPENAI_API_KEY

  ParameterStoreTelegramToken:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /examgpt/TG_BOT_TOKEN
      Type: String
      Value: TG_BOT_TOKEN

  ParameterStoreModelFamily:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /examgpt/MODEL_FAMILY
      Type: String
      Value: MODEL_FAMILY

  ParameterStoreModelName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /examgpt/MODEL_NAME
      Type: String
      Value: MODEL_NAME

  # DynamoDB
  ExamTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      KeySchema:
        - AttributeName: exam_code
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: exam_code
          AttributeType: S
      TableName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-exam

  ChatPersistenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      TableName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-chatpersistence

  # TODO: switch billing mode to use the full free tier capacity
  ChunkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-chunk
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      KeySchema:
        - AttributeName: chunk_id
          KeyType: HASH
        - AttributeName: exam_code
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: chunk_id
          AttributeType: S
        - AttributeName: exam_code
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: ExamIndex
          KeySchema:
            - AttributeName: exam_code
              KeyType: HASH
            - AttributeName: chunk_id
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 2
            WriteCapacityUnits: 2

  # Rest APIs
  ExamGPTRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  # Lambda Functions
  CreateExamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: entrypoints.api.create_exam.handler
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          CONTENT_BUCKET: !Ref ContentBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ContentBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ExamTable
      Events:
        APIEvent:
          Type: Api
          Properties:
            Path: /create_exam
            Method: POST
            RestApiId: !Ref ExamGPTRestApi

  ChunkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: entrypoints.api.chunker.handler
      MemorySize: 512
      Timeout: 600
      Environment:
        Variables:
          CHUNK_TOPIC: !Ref ChunkTopic
          CHUNK_TABLE: !Ref ChunkTable
          EXAM_TABLE: !Ref ExamTable
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ChunkTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref ChunkTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ExamTable
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref ContentBucket
            Events:
              - s3:ObjectCreated:*

  GenerateQAFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: entrypoints.api.generate.handler
      MemorySize: 128
      Timeout: 600
      Environment:
        Variables:
          CHUNK_TABLE: !Ref ChunkTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChunkTable
        - Statement:
            - Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
              Effect: Allow
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/examgpt*
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref ChunkTopic

  SandboxFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: entrypoints.api.sandbox.handler
      Events:
        APIEvent:
          Type: Api
          Properties:
            Path: /sandbox
            Method: POST
            RestApiId: !Ref ExamGPTRestApi

  ChatServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: examgpt_backend/
      Handler: entrypoints.api.chat_server.handler
      Timeout: 300
      MemorySize: 128
      Events:
        APIEvent:
          Type: Api
          Properties:
            Path: /chat
            Method: POST
            RestApiId: !Ref ExamGPTRestApi
      Environment:
        Variables:
          CHAT_PESISTENCE_TABLE: !Ref ChatPersistenceTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatPersistenceTable
        - Statement:
            - Action:
                - ssm:GetParameter
                - ssm:GetParameters
                - ssm:GetParametersByPath
              Effect: Allow
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/examgpt*

  # Connectors
  ChunkerFunctionContentBucketConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: ChunkerFunction
      Destination:
        Id: ContentBucket
      Permissions:
        - Read

Outputs:
  ExamGPTRestApi:
    Description: API Gateway endpoint for create_exam
    Value: !Sub https://${ExamGPTRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage
